Feature
tundeiness/Restaurant pull request #1
Opened 2019-11-18 08:37 UTC by tundeiness

2019-11-18 18:41 UTC, azdrenymeri requested changes
### Hello @tundeiness 👋 
#### Nice job on this project 👍 
#### There is this error 
*  Kindly remove the import of the `style.css` on the `index.html`.
   The `style.css` is already imported on your `index.js` `line 5: ( import './style.css'; )`:
`Failed to load resource: net::ERR_FILE_NOT_FOUND /C:/src/style.css:1 `
[Learn about Webpack loaders](https://medium.com/a-beginners-guide-for-webpack-2/webpack-loaders-css-and-sass-2cc0079b5b3a)
![scr](https://i.ibb.co/z2qXhDN/scr.png)

### kindly fix this issue and add it for a re-review

2019-11-18 18:41 UTC, azdrenymeri commented on src/contact.js
> +  // socials
kindly remove the comment

2019-11-18 18:41 UTC, azdrenymeri commented on src/menu.js
> +  // card container
Also here remove the comment.

2019-11-18 18:41 UTC, azdrenymeri commented on src/menu.js
> +  // first menu
And here

2019-11-19 10:25 UTC, shloch approved these changes
We are done here, nicely executed project

Great job @tundeiness  Omotunde

### You can merge this Request 😊😊

2019-11-19 11:01 UTC, merged